### ISSUE TITLE
Ask for assistance in .gitignore 

### ISSUE THREAD

**Issue by k3anton** [TimFra/IDKProject_MID2_PFID3#2]
Going on next week, asking @antonnyman for assistance on gitignore. Right now a lot of Android Studio files are uploaded each time, even with a gitignore in place. This causes some slight issues when people update their projects. 

A quick lookover might help ease the Github issues we've had so far.

**Comment by antonnyman** [comment]
Can you expand on the issues? I can meet up with you next week.

**Comment by k3anton** [comment]
Thanks for replying @antonnyman! 

Basically, we are 7 team members trying to collaborate on an android project. When we push and pull code from Github we sometimes trade Android Studio files with each other. This is not always a problem but it seems as if it could be done smoother. I remember you as being a GitHub-master and I've kind of taken that role in my team now. You could see our .gitignore. 

If you have time next week, I could clone the project and show you in detail what files that are being asked to add to git index. Workspace.xml for one is a trouble-maker. 

Our project room is B211. We are there between at least 9-16 every day. Come by and I'll treat you a coffee!

/Anton

**Comment by antonnyman** [comment]
I'll swing by this Monday or Tuesday. :)
Check out [this thread first](http://stackoverflow.com/questions/16736856/what-should-be-in-my-gitignore-for-an-android-studio-project).

**Comment by k3anton** [comment]
This is fixed, kind of.
